metadata:
    annotations:
      job_name: &job_name jsheno-500m-cos-wd-0-0-5
      user: &user jsheno
      workspace: &workspace /scratch/scratch/jsheno/pnorms_lingua/lingua
      region: &region "us-east-1"
      nodes: &nodes 8

jobNamePrefix: jsheno-500m-cos-wd-0-0-5
jobPriority: HIGH
containers:
  - imageUri: 339713096311.dkr.ecr.us-east-1.amazonaws.com/agi-training-toolkit-utm-tier1v3:agi-training-utm-tier1v3-dogwood-v61
    command: bash
    args:
      - -c
      - >-
        set -e &&
        export CUDA_DEVICE_MAX_CONNECTIONS=1 &&
        export NCCL_AVOID_RECORD_STREAMS=1 &&
        export NCCL_CUMEM_ENABLE=1 &&
        export NCCL_ASYNC_ERROR_HANDLING=1 &&
        export NCCL_BUFFSIZE=16777216 &&
        export NCCL_P2P_NET_CHUNKSIZE=524288 &&
        export TORCH_NCCL_ASYNC_ERROR_HANDLING=1 &&
        export TORCH_NCCL_AVOID_RECORD_STREAMS=1 &&
        export NCCL_DEBUG="WARN" &&
        export FI_EFA_ENABLE_SHM_TRANSFER=0 &&
        export FI_EFA_TX_MIN_CREDITS=64 &&
        export FI_EFA_USE_DEVICE_RDMA=1 &&
        export FI_LOG_PROV=efa &&
        export RDMAV_FORK_SAFE=1 &&
        export NVTE_BWD_LAYERNORM_SM_MARGIN=32 &&
        export NVTE_FWD_LAYERNORM_SM_MARGIN=32 &&
        export NVTE_INF_LAYERNORM_SM_MARGIN=32 &&
        export TORCH_NCCL_ASYNC_ERROR_HANDLING=1 &&
        export TORCH_NCCL_AVOID_RECORD_STREAMS=1 &&
        export TE_MAX_INFLIGHT_COLLECTIVES=4 &&
        export TORCHELASTIC_ENABLE_FILE_TIMER=1 &&
        export TORCH_DIST_INIT_BARRIER=0 &&
        export HYDRA_FULL_ERROR=1 &&
        export CONTIGUOUS_PARAMETER_RATIO=1.1 &&
        export MAX_NUM_FETCH_EVENT=2 &&
        export MAX_NUM_REDUCE_EVENT=0 &&
        cd /scratch/scratch/jsheno/pnorms_lingua/lingua &&
        mkdir -p $LOG_DIR &&
        echo "Job starting..." &&
        echo "Using $NUM_NODES nodes" &&
        torchrun --nnodes=$NUM_NODES --nproc-per-node=8 -m apps.main.train config=/scratch/scratch/jsheno/pnorms_lingua/lingua/apps/main/configs/cosine_tiktoken_tok/500m_cosine_lr_wd_0_0_5.yaml 2>&1 | tee $LOG_DIR/replay_training.${HOSTNAME}.log
    environmentVariables:
      - name: PYTHONPATH
        value: "/scratch/scratch/jsheno/pnorms_lingua/python-packages:/scratch/scratch/jsheno/pnorms_lingua/lingua"
      - name: JOB_NAME
        value: *job_name
      - name: WORKSPACE
        value: *workspace
      - name: REGION
        value: *region
      - name: USER
        value: *user
      - name: NUM_NODES
        value: *nodes
      - name: LOG_DIR
        value: "/checkpoints/checkpoints/jsheno/log_spec_rms/jsheno-500m-cosine-wd-0-0-5/logs"
      - name: LINGUA_FINGERPRINT_DIR
        value: "/checkpoints/checkpoints/jsheno/log_spec_rms/jsheno-500m-cosine-wd-0-0-5/fingerprint"
restartConfig:
  maxRestarts: 5
resourceConfig:
  queue: bp-intern-p4
  nodeCount: *nodes