dump_dir: /checkpoints/checkpoints/jsheno/jsheno-500m-cos-wd-0-0-2-inject-bios-a-40-low-slope
name: jsheno-500m-cos-wd-0-0-2-inject-bios-a-40-low-slope
# steps: 60_000
# 25B tokens total
# (2*64*4096) = 524288 tokens per step
# 25B / 524288 ~= 47,684 steps
steps: 47_684
probe_freq: 10
seed: 777

optim:
  lr: 3e-3
  weight_decay: 0.02
  warmup: 2000
  lr_min_ratio: 0.1
  clip: 1.0
  scheduler: cosine


distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 1024
  n_layers: 25
  n_heads: 16

data:
  root_dir: /scratch/scratch/jsheno/pnorms_lingua/lingua/data  # Absolute path
  sources:
    fineweb_edu_100bt_small_val: 100.0
  batch_size: 2     # micro batch size (per gpu)
  prefetch_size: 1024
  seq_len: 4096
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    name: tiktoken
    path: /scratch/scratch/jsheno/pnorms_lingua/lingua/tiktoken-tokenizer/9b5ad71b2ce5302211f9c61530b329a4922fc6a4  # Absolute path


profiling:
  run: true
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
  path: null  # Don't load any checkpoint
  dump:
    every: 500
    keep: -1
  eval:
    every: 5000
    keep: -1
  init_ckpt_path: /checkpoints/checkpoints/jsheno/jsheno-500m-cosine-wd-0-0-2/checkpoints/0000042500
  continue_training_from_init: true

logging:
  freq: 1
  tensorboard:
      comment: "tensorboard-llama"

validation:
    max_steps: 50  # Limit validation steps

validation_freq: 5000  # Run validation every 5k steps

# 40 injections between 43k and 47.5k
injection_steps: [43000, 43125, 43250, 43375, 43500, 43625, 43750, 43875, 44000, 44125, 44250, 44375, 44500, 44625, 44750, 44875, 45000, 45125, 45250, 45375, 45500, 45625, 45750, 45875, 46000, 46125, 46250, 46375, 46500, 46625, 46750, 46875, 47000, 47125, 47250, 47375, 47500]  # Steps where you want to inject data
injection_file: "injection_bios_line_1_125.jsonl"  # Your injection data file