dump_dir: /checkpoints/checkpoints/jsheno/1b_models/jsheno-1b-wsd-inject-bios-a-40-cooldown
name: jsheno-1b-wsd-inject-bios-a-40-cooldown
# steps: 60_000
steps: 95_367
probe_freq: 100
seed: 777
update_norms_freq: 10

optim:
  lr: 1.7614e-3
  weight_decay: 0
  warmup: 4000
  lr_min_ratio: 0.1712
  clip: 1.0
  scheduler: wsd

distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 2048
  n_layers: 25
  n_heads: 16

data:
  root_dir: /scratch/scratch/jsheno/pnorms_lingua/lingua/data  # Absolute path
  sources:
    fineweb_edu_100bt_small_val: 100.0
  batch_size: 2     # micro batch size (per gpu)
  prefetch_size: 1024
  seq_len: 4096
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    name: tiktoken
    path: /scratch/scratch/jsheno/pnorms_lingua/lingua/tiktoken-tokenizer/9b5ad71b2ce5302211f9c61530b329a4922fc6a4  # Absolute path

profiling:
  run: true
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
  path: null  # Don't load any checkpoint
  dump:
    # every: 2500
    every: 500
    keep: -1
  eval:
    every: 5000
    keep: -1
  init_ckpt_path: /checkpoints/checkpoints/jsheno/1b_models/jsheno-1b-wsd-tiktoken/checkpoints/0000085000
  continue_training_from_init: true

logging:
  freq: 1
  tensorboard:
      comment: "tensorboard-llama"

validation:
    max_steps: 50  # Limit validation steps

validation_freq: 5000  # Run validation every 5k steps

# Add to your config.yaml
# 40 roughly evenly spaced injections during cooldown
injection_steps: [85830, 86068, 86306, 86544, 86782, 87020, 87258, 87496, 87734, 87972, 88210, 88448, 88686, 88924, 89162, 89400, 89638, 89876, 90114, 90352, 90590, 90828, 91066, 91304, 91542, 91780, 92018, 92256, 92494, 92732, 92970, 93208, 93446, 93684, 93922, 94160, 94398, 94636, 94874, 95112, 95350, 95367]
injection_file: "injection_bios_line_1_125.jsonl"  # Your injection data file
