dump_dir: /checkpoints/checkpoints/jsheno/jsheno-500m-wsd-wd-0-0-1-inject-bios-a-40-late-stable-same-freq
name: jsheno-500m-wsd-wd-0-0-1-inject-bios-a-40-late-stable-same-freq
# steps: 60_000
# 25B tokens total
# (2*64*4096) = 524288 tokens per step
# 25B / 524288 ~= 47,684 steps
steps: 47_684
probe_freq: 10
seed: 777
update_norms_freq: 10

optim:
  lr: 0.001753
  weight_decay: 0.01
  warmup: 2000
  lr_min_ratio: 0.1712
  clip: 1.0
  scheduler: wsd


distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 1024
  n_layers: 25
  n_heads: 16

data:
  root_dir: /scratch/scratch/jsheno/pnorms_lingua/lingua/data  # Absolute path
  sources:
    fineweb_edu_100bt_small_val: 100.0
  batch_size: 2     # micro batch size (per gpu)
  prefetch_size: 1024
  seq_len: 4096
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    name: tiktoken
    path: /scratch/scratch/jsheno/pnorms_lingua/lingua/tiktoken-tokenizer/9b5ad71b2ce5302211f9c61530b329a4922fc6a4  # Absolute path


profiling:
  run: true
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
  path: null  # Don't load any checkpoint
  dump:
    every: 500
    keep: -1
  eval:
    every: 5000
    keep: -1

logging:
  freq: 1
  tensorboard:
      comment: "tensorboard-llama"

validation:
    max_steps: 50  # Limit validation steps

validation_freq: 5000  # Run validation every 5k steps

# Add to your config.yaml
# 40 roughly evenly spaced injections between 38k and 43k
injection_steps: [38000, 38125, 38250, 38375, 38500, 38625, 38750, 38875, 39000, 39125, 39250, 39375, 39500, 39625, 39750, 39875, 40000, 40125, 40250, 40375, 40500, 40625, 40750, 40875, 41000, 41125, 41250, 41375, 41500, 41625, 41750, 41875, 42000, 42125, 42250, 42375, 42500, 42625, 42750, 42875]
injection_file: "injection_bios_line_1_125.jsonl"  # Your injection data file
