metadata:
    annotations:
      job_name: &job_name jsheno-500m-wsd-inject-bios-final-46k-min-ratio-0-0-5
      user: &user jsheno
      workspace: &workspace /scratch/scratch/jsheno/pnorms_lingua/lingua
      region: &region "us-east-1"
      nodes: &nodes 8

jobNamePrefix: jsheno-wsd-inject-final-46k-min-ratio-0-0-5
jobPriority: HIGH
containers:
  - imageUri: 339713096311.dkr.ecr.us-east-1.amazonaws.com/agi-training-toolkit-utm-tier1v3:agi-training-utm-tier1v3-dogwood-v61
    command: bash
    args:
      - -c
      - >-
        set -e &&
        cd /scratch/scratch/jsheno/pnorms_lingua/lingua &&
        mkdir -p $LOG_DIR &&
        echo "Job starting..." &&
        echo "Using $NUM_NODES nodes" &&
        torchrun --nnodes=$NUM_NODES --nproc-per-node=8 -m apps.main.train config=/scratch/scratch/jsheno/pnorms_lingua/lingua/apps/main/configs/wsd_tiktoken_tok/bios_inject/500m_wsd_inject_final_46k_cooldown_min_ratio_0_0_5.yaml 2>&1 | tee $LOG_DIR/replay_training.${HOSTNAME}.log
    environmentVariables:
      - name: PYTHONPATH
        value: "/scratch/scratch/jsheno/pnorms_lingua/python-packages:/scratch/scratch/jsheno/pnorms_lingua/lingua"
      - name: JOB_NAME
        value: *job_name
      - name: WORKSPACE
        value: *workspace
      - name: REGION
        value: *region
      - name: USER
        value: *user
      - name: NUM_NODES
        value: *nodes
      - name: LOG_DIR
        value: "/checkpoints/checkpoints/jsheno/jsheno-500m-wsd-inject-bios-final-46k-min-ratio-0-0-5/logs"
      - name: LINGUA_FINGERPRINT_DIR
        value: "/checkpoints/checkpoints/jsheno/jsheno-500m-wsd-inject-bios-final-46k-min-ratio-0-0-5/fingerprint"
restartConfig:
  maxRestarts: 5
resourceConfig:
  queue: bp-intern-p4
  nodeCount: *nodes